# Generated by Django 6.1.1 on 2026-09-26 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_empresa', models.CharField(max_length=200)),
                ('cliente_contacto', models.CharField(max_length=200)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('descripcion_proyecto', models.TextField()),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(default='en_evaluacion', max_length=50)),
                ('fecha', models.DateField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='consultoria.serviciomodel')),
            ],
        ),
    ]
